---
- hosts: all

  vars_files:
    - ../common/base_vars.yaml

  tasks:
    - name: stop mds
      command: ./mds stop -F
      args:
        chdir: "{{ slave_path_mds_home_bin }}"
      ignore_errors: yes

    - name: archive mds package
      archive:
        path:
          - "{{ slave_path_mds_home_bin }}"
          - "{{ slave_path_mds_home_conf }}"
          - "{{ slave_path_mds_home_data }}"
          - "{{ slave_path_mds_home_logs }}"
          - "{{ slave_path_mds_home_art }}"
          - "{{ slave_path_mds_home_sbin }}"
          - "{{ slave_path_mds_home_sample }}"
        dest: "{{ slave_backup_path }}/{{ pkg_name }}.tar.gz"
        remove: False
      run_once: true
      ignore_errors: True
