################ crd计划任务 #######################
# 本配置仅用于创建crd集群时自动注册的计划任务时间
# 计划任务实际注册时间以数据库为准
mon: 
  script_name: "mon.sh"
  script_label: "cmd"
  specification: "30 6 * * 1-5"
counter_fetch: 
  script_name: "counter_fetch.sh"
  script_label: "cmd"
  specification: "30 7 * * 1-5"
counter_distribute: 
  script_name: "counter_distribute.sh"
  script_label: "cmd"
  specification: "40 7 * * 1-5"
sse: 
  script_name: "sse.sh"
  script_label: "cmd"
  specification: "5 8 * * 1-5"
szse: 
  script_name: "szse.sh"
  script_label: "cmd"
  specification: "36 7 * * 1-5"
csdc: 
  script_name: "csdc.sh"
  script_label: "cmd"
  specification: "35 7 * * 1-5"
sse_late: 
  script_name: "sse_late.sh"
  script_label: "cmd"
  specification: "5 8 * * 1-5"
szse_late: 
  script_name: "szse_late.sh"
  script_label: "cmd"
  specification: "36 7 * * 1-5"
backup: 
  script_name: "backup.sh"
  script_label: "cmd"
  specification: "0 20 * * 1-5"
################ crd计划任务 #######################

