################ stk计划任务 #######################
# 本配置仅用于创建stk集群时自动注册的计划任务时间
# 计划任务实际注册时间以数据库为准

mon: 
  script_id: 26
  specification: "30 6 * * 1-5"
counter_fetch: 
  script_id: 27
  specification: "30 7 * * 1-5"
counter_distribute: 
  script_id: 28
  specification: "40 7 * * 1-5"
bse: 
  script_id: 29
  specification: "2 8 * * 1-5"
sse: 
  script_id: 30
  specification: "5 8 * * 1-5"
szse: 
  script_id: 31
  specification: "36 7 * * 1-5"
csdc: 
  script_id: 32
  specification: "35 7 * * 1-5"
backup: 
  script_id: 35
  specification: "0 20 * * 1-5"
################ stk计划任务 #######################
