---
- hosts: all

  vars_files:
    - ../common/base_vars.yaml

  tasks:
    - name: load automatic variables
      include_vars: "{{ local_path_oes_home_config_all }}/automatic.yaml"
      delegate_to: 127.0.0.1
      run_once: true

    - name: mkdir local zb dirs
      file:
        path: "{{ local_path_oes_home_zb_colodir }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ zb_dir.split(',') | select('length', '>', 0) | list }}"
      delegate_to: 127.0.0.1
      run_once: true

    - name: fetch remote mds_zb file
      command: "rsync -az --exclude='*/' -e 'ssh -p {{ zb_port }}' {{ zb_user }}@{{ zb_host }}:{{ zb_path }}/{{ item }}/ {{ local_path_oes_home_zb_colodir }}/{{ item }}/"
      with_items: "{{ zb_dir.split(',') | select('length', '>', 0) | list }}"
      ignore_errors: yes
      delegate_to: 127.0.0.1
      run_once: true

    - name: mkdir remote mds zb dirs
      file:
        path: "{{ slave_path_mds_home }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ zb_dir.split(',') | select('length', '>', 0) | list }}"

    - name: send zb file to mds
      synchronize:
        src: "{{ local_path_mds_home_zb_colodir }}/{{ item }}/"
        dest: "{{ slave_path_mds_home }}/{{ item }}/"
        checksum: yes
      with_items: "{{ zb_dir.split(',') | select('length', '>', 0) | list }}"
      ignore_errors: yes