---

- name: create mon save counter directory
  command: ssh -p {{ mon_host.ansible_port }} {{ mon_host.ansible_user }}@{{ mon_host.ansible_host }} "rm -rf {{ mon_save_counter_path }} && mkdir -p {{ mon_save_counter_path }}"
  delegate_to: 127.0.0.1
  run_once: true
  ignore_errors: yes

- name: send xcounter files to mon
  command: rsync -az -e 'ssh -p {{ mon_host.ansible_port }}' {{ local_path_oes_home_counter_colodir_data_broker }}/ {{ mon_host.ansible_user }}@{{ mon_host.ansible_host }}:{{ mon_save_counter_path }}/
  delegate_to: 127.0.0.1
  run_once: true
  ignore_errors: yes
