---
- hosts: all

  vars_files:
    - ../common/base_vars.yaml

  tasks:
    - name: stop oes
      command: ./oes stop -F
      args:
        chdir: "{{ slave_path_oes_home_bin }}"
      ignore_errors: yes

    - name: archive oes package
      archive:
        path:
          - "{{ slave_path_oes_home_bin }}"
          - "{{ slave_path_oes_home_conf }}"
          - "{{ slave_path_oes_home_data }}"
          - "{{ slave_path_oes_home_logs }}"
          - "{{ slave_path_oes_home_art }}"
          - "{{ slave_path_oes_home_sbin }}"
          - "{{ slave_path_oes_home_sample }}"
        dest: "{{ slave_backup_path }}/{{ pkg_name }}.tar.gz"
        remove: False
      ignore_errors: True
