// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/customer/menu": {
            "get": {
                "description": "本接口用于查询菜单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "查询菜单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回菜单列表",
                        "schema": {
                            "$ref": "#/definitions/menu.PagMenuBaseReply"
                        }
                    }
                }
            },
            "post": {
                "description": "本接口用于新增菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "新增菜单",
                "parameters": [
                    {
                        "description": "创建菜单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu.CreateMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回菜单信息",
                        "schema": {
                            "$ref": "#/definitions/menu.MenuReply"
                        }
                    }
                }
            }
        },
        "/api/v1/customer/menu/{pk}": {
            "get": {
                "description": "本接口用于查询一个菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "查询单个菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单编号",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户信息",
                        "schema": {
                            "$ref": "#/definitions/menu.MenuReply"
                        }
                    }
                }
            },
            "put": {
                "description": "本接口用于更新菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单编号",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新菜单请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/menu.UpdateMenuRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回菜单信息",
                        "schema": {
                            "$ref": "#/definitions/menu.MenuReply"
                        }
                    }
                }
            },
            "delete": {
                "description": "本接口用于删除指定ID的菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单管理"
                ],
                "summary": "删除菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单编号",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/exception.Reply-map_string_string"
                        }
                    }
                }
            }
        },
        "/api/v1/customer/permission": {
            "get": {
                "description": "本接口用于查询权限列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "查询权限列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "权限主键，可选参数，如果提供则必须大于0",
                        "name": "pk",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "权限主键列表，可选参数，多个用,隔开，如1,2,3",
                        "name": "pks",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间之前的记录 (RFC3339格式)",
                        "name": "before_create_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间之后的记录 (RFC3339格式)",
                        "name": "after_create_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间之前的记录 (RFC3339格式)",
                        "name": "before_update_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "更新时间之后的记录 (RFC3339格式)",
                        "name": "after_update_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "HTTP路径",
                        "name": "http_url",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "HTTP方法",
                        "name": "method",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回权限列表",
                        "schema": {
                            "$ref": "#/definitions/permission.PagPermissionReply"
                        }
                    }
                }
            },
            "post": {
                "description": "本接口用于新增权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "新增权限",
                "parameters": [
                    {
                        "description": "创建权限请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/permission.CreatePermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回权限信息",
                        "schema": {
                            "$ref": "#/definitions/permission.PermissionReply"
                        }
                    }
                }
            }
        },
        "/api/v1/customer/permission/{pk}": {
            "get": {
                "description": "本接口用于查询一个权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "查询单个权限",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "权限编号",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户信息",
                        "schema": {
                            "$ref": "#/definitions/permission.PermissionReply"
                        }
                    }
                }
            },
            "put": {
                "description": "本接口用于更新权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "更新权限",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "权限编号",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新权限请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/permission.UpdatePermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回权限信息",
                        "schema": {
                            "$ref": "#/definitions/permission.PermissionReply"
                        }
                    }
                }
            },
            "delete": {
                "description": "本接口用于删除指定ID的权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "权限管理"
                ],
                "summary": "删除权限",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "权限编号",
                        "name": "pk",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/exception.Reply-map_string_string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.Pag-menu_MenuOutBase": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "对象数组",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/menu.MenuOutBase"
                    }
                },
                "page": {
                    "description": "当前页码\nExample: 1",
                    "type": "integer",
                    "example": 1
                },
                "pages": {
                    "description": "总页数\nExample: 10",
                    "type": "integer",
                    "example": 10
                },
                "size": {
                    "description": "每页数量\nExample: 10",
                    "type": "integer",
                    "example": 10
                },
                "total": {
                    "description": "总记录数\nExample: 100",
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "database.Pag-permission_PermissionOutBase": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "对象数组",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/permission.PermissionOutBase"
                    }
                },
                "page": {
                    "description": "当前页码\nExample: 1",
                    "type": "integer",
                    "example": 1
                },
                "pages": {
                    "description": "总页数\nExample: 10",
                    "type": "integer",
                    "example": 10
                },
                "size": {
                    "description": "每页数量\nExample: 10",
                    "type": "integer",
                    "example": 10
                },
                "total": {
                    "description": "总记录数\nExample: 100",
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "exception.Reply-map_string_string": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码\nExample: 200",
                    "type": "integer"
                },
                "data": {
                    "description": "数据\n可以是任意类型的数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/map_string_string"
                        }
                    ]
                },
                "msg": {
                    "description": "信息\nExample: \"success\"",
                    "type": "string"
                }
            }
        },
        "map_string_string": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "menu.CreateMenuRequest": {
            "type": "object",
            "required": [
                "component",
                "id",
                "meta",
                "name",
                "path"
            ],
            "properties": {
                "arrange_order": {
                    "description": "排序字段，可选",
                    "type": "integer"
                },
                "component": {
                    "description": "组件路径，必填，最大长度200\nRequired: true\nMax length: 200",
                    "type": "string",
                    "maxLength": 200
                },
                "descr": {
                    "description": "菜单描述信息，可选，最大长度254\nMax length: 254",
                    "type": "string",
                    "maxLength": 254
                },
                "id": {
                    "description": "菜单主键，必填，必须大于0\nRequired: true\nMinimum: 1",
                    "type": "integer"
                },
                "is_active": {
                    "description": "是否激活，可选",
                    "type": "boolean"
                },
                "meta": {
                    "description": "菜单元信息，必填",
                    "allOf": [
                        {
                            "$ref": "#/definitions/menu.MetaSchemas"
                        }
                    ]
                },
                "name": {
                    "description": "菜单名称，必填，最大长度50\nRequired: true\nMax length: 50",
                    "type": "string",
                    "maxLength": 50
                },
                "parent_id": {
                    "description": "父级菜单ID，可选",
                    "type": "integer"
                },
                "path": {
                    "description": "前端路由路径，必填，最大长度100\nRequired: true\nMax length: 100",
                    "type": "string",
                    "maxLength": 100
                },
                "permission_ids": {
                    "description": "关联权限ID列表，可选",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "menu.MenuOut": {
            "type": "object",
            "properties": {
                "arrange_order": {
                    "description": "排列顺序",
                    "type": "integer",
                    "example": 1000
                },
                "create_at": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2023-01-01 12:00:00"
                },
                "descr": {
                    "description": "描述",
                    "type": "string",
                    "example": "用户管理"
                },
                "id": {
                    "description": "权限ID",
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "description": "是否激活",
                    "type": "boolean",
                    "example": true
                },
                "meta": {
                    "description": "菜单信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/menu.MetaSchemas"
                        }
                    ]
                },
                "name": {
                    "description": "名称",
                    "type": "string",
                    "example": "用户管理"
                },
                "parent": {
                    "$ref": "#/definitions/menu.MenuOutBase"
                },
                "path": {
                    "description": "前端路由",
                    "type": "string",
                    "example": "/api/v1/users"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/permission.PermissionOutBase"
                    }
                },
                "update_at": {
                    "description": "更新时间",
                    "type": "string",
                    "example": "2023-01-01 12:00:00"
                },
                "xomponent": {
                    "description": "组件路径",
                    "type": "string",
                    "example": "GET"
                }
            }
        },
        "menu.MenuOutBase": {
            "type": "object",
            "properties": {
                "arrange_order": {
                    "description": "排列顺序",
                    "type": "integer",
                    "example": 1000
                },
                "create_at": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2023-01-01 12:00:00"
                },
                "descr": {
                    "description": "描述",
                    "type": "string",
                    "example": "用户管理"
                },
                "id": {
                    "description": "权限ID",
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "description": "是否激活",
                    "type": "boolean",
                    "example": true
                },
                "meta": {
                    "description": "菜单信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/menu.MetaSchemas"
                        }
                    ]
                },
                "name": {
                    "description": "名称",
                    "type": "string",
                    "example": "用户管理"
                },
                "path": {
                    "description": "前端路由",
                    "type": "string",
                    "example": "/api/v1/users"
                },
                "update_at": {
                    "description": "更新时间",
                    "type": "string",
                    "example": "2023-01-01 12:00:00"
                },
                "xomponent": {
                    "description": "组件路径",
                    "type": "string",
                    "example": "GET"
                }
            }
        },
        "menu.MenuReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码\nExample: 200",
                    "type": "integer"
                },
                "data": {
                    "description": "数据\n可以是任意类型的数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/menu.MenuOut"
                        }
                    ]
                },
                "msg": {
                    "description": "信息\nExample: \"success\"",
                    "type": "string"
                }
            }
        },
        "menu.MetaSchemas": {
            "type": "object",
            "properties": {
                "icon": {
                    "description": "图标",
                    "type": "string",
                    "example": "icon"
                },
                "title": {
                    "description": "标题",
                    "type": "string",
                    "example": "用户管理"
                }
            }
        },
        "menu.PagMenuBaseReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码\nExample: 200",
                    "type": "integer"
                },
                "data": {
                    "description": "数据\n可以是任意类型的数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/database.Pag-menu_MenuOutBase"
                        }
                    ]
                },
                "msg": {
                    "description": "信息\nExample: \"success\"",
                    "type": "string"
                }
            }
        },
        "menu.UpdateMenuRequest": {
            "type": "object",
            "required": [
                "component",
                "meta",
                "name",
                "path"
            ],
            "properties": {
                "arrange_order": {
                    "description": "排序字段，可选",
                    "type": "integer"
                },
                "component": {
                    "description": "组件路径，必填，最大长度200\nRequired: true\nMax length: 200",
                    "type": "string",
                    "maxLength": 200
                },
                "descr": {
                    "description": "菜单描述信息，可选，最大长度254\nMax length: 254",
                    "type": "string",
                    "maxLength": 254
                },
                "is_active": {
                    "description": "是否激活，可选",
                    "type": "boolean"
                },
                "meta": {
                    "description": "菜单元信息，必填",
                    "allOf": [
                        {
                            "$ref": "#/definitions/menu.MetaSchemas"
                        }
                    ]
                },
                "name": {
                    "description": "菜单名称，必填，最大长度50\nRequired: true\nMax length: 50",
                    "type": "string",
                    "maxLength": 50
                },
                "parent_id": {
                    "description": "父级菜单ID，可选",
                    "type": "integer"
                },
                "path": {
                    "description": "前端路由路径，必填，最大长度100\nRequired: true\nMax length: 100",
                    "type": "string",
                    "maxLength": 100
                },
                "permission_ids": {
                    "description": "关联权限ID列表，可选",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "permission.CreatePermissionRequest": {
            "type": "object",
            "required": [
                "http_url",
                "id",
                "method"
            ],
            "properties": {
                "descr": {
                    "description": "权限描述信息，可选，最大长度254\nMax length: 254",
                    "type": "string",
                    "maxLength": 254
                },
                "http_url": {
                    "description": "权限对应的HTTP URL，必填，最大长度150\nRequired: true\nMax length: 150",
                    "type": "string",
                    "maxLength": 150
                },
                "id": {
                    "description": "权限主键，必填，必须大于0\nRequired: true\nMinimum: 1",
                    "type": "integer"
                },
                "method": {
                    "description": "HTTP请求方法，必填，枚举值验证\nRequired: true\nEnum: GET,POST,PUT,DELETE,PATCH,WS",
                    "type": "string",
                    "enum": [
                        "GET",
                        "POST",
                        "PUT",
                        "DELETE",
                        "PATCH",
                        "WS"
                    ]
                }
            }
        },
        "permission.PagPermissionReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码\nExample: 200",
                    "type": "integer"
                },
                "data": {
                    "description": "数据\n可以是任意类型的数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/database.Pag-permission_PermissionOutBase"
                        }
                    ]
                },
                "msg": {
                    "description": "信息\nExample: \"success\"",
                    "type": "string"
                }
            }
        },
        "permission.PermissionOutBase": {
            "type": "object",
            "properties": {
                "create_at": {
                    "description": "创建时间",
                    "type": "string",
                    "example": "2023-01-01 12:00:00"
                },
                "descr": {
                    "description": "描述",
                    "type": "string",
                    "example": "用户管理权限"
                },
                "http_url": {
                    "description": "HTTP路径",
                    "type": "string",
                    "example": "/api/v1/users"
                },
                "id": {
                    "description": "权限ID",
                    "type": "integer",
                    "example": 1
                },
                "method": {
                    "description": "请求方法",
                    "type": "string",
                    "example": "GET"
                },
                "update_at": {
                    "description": "更新时间",
                    "type": "string",
                    "example": "2023-01-01 12:00:00"
                }
            }
        },
        "permission.PermissionReply": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码\nExample: 200",
                    "type": "integer"
                },
                "data": {
                    "description": "数据\n可以是任意类型的数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/permission.PermissionOutBase"
                        }
                    ]
                },
                "msg": {
                    "description": "信息\nExample: \"success\"",
                    "type": "string"
                }
            }
        },
        "permission.UpdatePermissionRequest": {
            "type": "object",
            "required": [
                "http_url",
                "method"
            ],
            "properties": {
                "descr": {
                    "description": "权限描述信息，可选，最大长度254\nMax length: 254",
                    "type": "string",
                    "maxLength": 254
                },
                "http_url": {
                    "description": "权限对应的HTTP URL，必填，最大长度150\nRequired: true\nMax length: 150",
                    "type": "string",
                    "maxLength": 150
                },
                "method": {
                    "description": "HTTP请求方法，必填，枚举值验证\nRequired: true\nEnum: GET,POST,PUT,DELETE,PATCH,WS",
                    "type": "string",
                    "enum": [
                        "GET",
                        "POST",
                        "PUT",
                        "DELETE",
                        "PATCH",
                        "WS"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
